server:
  port: 8080
debug: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itning?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0
    username: root
    password: kingston
  thymeleaf:
    cache: false
    mode: HTML
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      enabled: detect # 控制台输出 多彩
security:
  user:
    name: 1
    password: 1
logging:
  level: debug