server:
  port: 80
debug: false
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itning?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0
    username: root
    password: kingston
  thymeleaf:
    cache: true
    mode: HTML
  mvc:
    favicon:
      enabled: false
security:
  user:
    name: 用户名
    password: 密码
logging:
  level: error